trigger:
- azure-pipelines

strategy:
  matrix:
    linux_s3:
      imageName: 'ubuntu-16.04'
      TILEDB_S3: ON
      CXX: g++
    linux_hdfs:
      imageName: 'ubuntu-16.04'
      variables:
      TILEDB_HDFS: ON
      CXX: g++
    linux_asan:
      imageName: 'ubuntu-16.04'
      TILEDB_CI_ASAN: ON
      TILEDB_TBB: OFF
      CXX: g++-7
    linux_tsan:
      imageName: 'ubuntu-16.04'
      TILEDB_CI_TSAN: ON
      TILEDB_TBB: OFF
      CXX: g++-7
    mac:
      imageName: 'macOS-10.13'
      TILEDB_S3: ON
      TILEDB_DEBUG: ON
      CXX: clang++
    #windows:
    #  imageName: 'vs2017-win2016'
  maxParallel: 4

pool:
  vmImage: $(imageName)

steps:
# we need this for virtualenv, used for the docs build
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: |
    git clone https://github.com/TileDB-Inc/TileDB-Unit-Test-Arrays.git test/inputs/arrays/read_compatibility_test
  displayName: 'Clone Unit-Test-Arrays'

- bash: scripts/azure-linux_mac.yaml
  displayName: 'Install, build, and test for Linux/Mac'
  condition: ne(variables['Agent.OS'], 'Windows_NT')
